### ISSUE TITLE
CSS shorthand properties overwrite higher priority standard properties 

### ISSUE THREAD

**Issue by josh18** [tijsverkoyen/CssToInlineStyles#140]
**Example**
```css
td.body-cell  {
    padding-bottom: 20px;
}

td {
    padding: 0;
}
```

**Expected Result**
```css
padding: 0;
padding-bottom: 20px;
```

**Observed Result**
```css
padding-bottom: 20px;
padding: 0;
```

**Comment by josh18** [comment]
I think you just need to add `usort($objects, 'self::sortOnSpecificity');` around line 131 of `src/Css/Rule/Processor.php`?

**Comment by josh18** [comment]
With the above fix there is still a rare case where this occurs:

**Example**
```css
td  {
    padding: 0;
}

td  {
    padding-bottom: 20px;
}

td  {
    padding: 0;
}
```

**Expected Result**
```
padding-bottom: 20px;
padding: 0;
```


**Observed Result**
```
padding: 0;
padding-bottom: 20px
```

To fix this we just need to add `unset($cssProperties[$property->getName()]);` before setting the property (line 209 - 232 of `src/CssToInlineStyles.php`) so that the order from the new property is resected.

Let me know if you want me to create a pull request.
