### ISSUE TITLE
Any plans on adding CSS variables support?

### ISSUE THREAD

**Issue by osbre** [tijsverkoyen/CssToInlineStyles#206]
https://developer.mozilla.org/en-US/docs/Web/CSS/var()

**Comment by stof** [comment]
what do you need exactly as support for CSS variables ?

**Comment by osbre** [comment]
I was thinking about

```css
:root {
    --fg-color: rgb(55, 53, 47);
}

.notion {
  color: var(--fg-color);
}
```

Which results in

```html
<div class="notion" style="color: rgb(55, 53, 47)"></div>
```
