### ISSUE TITLE
Semicolon and base64

### ISSUE THREAD

**Issue by SlowProg** [tijsverkoyen/CssToInlineStyles#92]
Hi,

I have style with base64:

```css
.bg {
background-image: url('data:image/jpg;base64,/9j/4QAYRXhpZgAASUkqAAgAA//Z');
}
```

After convert it's looks like that:

```html
<table class="bg" style="background-image: url('data:image/jpg;">
```
