### ISSUE TITLE
Styles in media query overwriting base styles

### ISSUE THREAD

**Issue by stevenmusumeche** [tijsverkoyen/CssToInlineStyles#94]
I have the following CSS:

```css
<style type="text/css">
    @media only screen and (max-width: 480px) {
        /* mobile-specific CSS styles go here */
        table.container {
            width: 460px !important;
        }
    }
    table.container {
        width: 600px;
    }
</style>
```

The idea is that `table.container` is 600px on normal devices, and 460px on mobile devices.  When I run this code through CssToInlineStyles, it is using the 460px version inline.  For example:

```html
<table class="container" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 460px !important;">
.....
```

How can I structure my media query so that the 600px version is used inline?
